version: '2'

services:
  app:
    image: 'locacionesbackend:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8181
          
  db:
    image: 'postgres:14.2-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      
  fe:
    image: 'locacionesfrontend:latest'
    build:
      context: .
    container_name: fe
    depends_on:
      - app
    
    ports:
      - 4200:80
  
      
